"""empty message

Revision ID: c26daef900d2
Revises: 
Create Date: 2023-09-12 13:18:25.275101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26daef900d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_room')
    op.drop_index('ix_question_category', table_name='question')
    op.drop_index('ix_question_game_name', table_name='question')
    op.drop_table('question')
    op.drop_table('answer')
    op.drop_index('ix_player_name', table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('game_rooms_played', sa.INTEGER(), nullable=False),
    sa.Column('game_rooms_won', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('game_room_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_room_id'], ['game_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_player_name', 'player', ['name'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('points', sa.FLOAT(), nullable=True),
    sa.Column('correct', sa.BOOLEAN(), nullable=True),
    sa.Column('question_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_name', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('text', sa.VARCHAR(), nullable=False),
    sa.Column('excluded', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_game_name', 'question', ['game_name'], unique=False)
    op.create_index('ix_question_category', 'question', ['category'], unique=False)
    op.create_table('game_room',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_name', sa.VARCHAR(), nullable=False),
    sa.Column('game_category', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
